(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["WKB`"];
Unprotect[SeriesSolve,WKBOrderList,WKBPade,BasicWKBFormula,WKBFormulaOrder,ThisPoint,PadeAverage,WKBFormula,WKBFormulaPade,WKBCoeff,WKBCoeffPade,SolveEikonal,QNMCoeff,GBFactor];
Begin["`Private`"];


(*Read data from file*)
ReadCompressedData[filename_String]:=With[{stream=OpenRead[filename,BinaryFormat->True]},If[stream===$Failed,$Failed,With[{result=Check[Read[stream,String]//Uncompress,$Failed]},Close[stream];result]]];


(*Read file WKBorders from the Package directory*)
WKBordersfilename=DirectoryName[$Input]<>"WKBorders";
(*Error message*)
WKBFormulaOrder::filecorrupt="Unable to load higher-order WKB formula from "<>WKBordersfilename<>". Only third-order formula can be used.";


(*Restore correct WKB orders by adding the multipliers*)
WKBOrderFactors[len_,WKB_]:=MapAt[(-I*WKB[[2]]*#)&,Join[{WKB//First,1},Drop[WKB,2]],{Range[2,len,2]}//Transpose];
(*Check raw data from the file*)
CheckWKBData[{credits_String,fList:{__Symbol},vList:{__Symbol},derexpr_List,K_Symbol,VList:{__Symbol},ListOfWKBOrders_List}]:=With[{flen=fList//Length,vlen=vList//Length,dlen=derexpr//Length,Vlen=VList//Length,order=Length[ListOfWKBOrders]-1},
{order,credits,fList,vList,derexpr,Prepend[VList,K],WKBOrderFactors[order+1,ListOfWKBOrders]}/;flen+1==vlen==dlen==Vlen==order*2&&vList[[1]]===derexpr[[1]]&&VList[[1]]===ListOfWKBOrders[[1]]&&K*Sqrt[-2*VList[[2]]]===ListOfWKBOrders[[2]]
];
(*Error handle*)
CheckWKBData[___]:=With[{DefaultWKBOrder={V0,t*Sqrt[-2*V2],(-7*V3^2-60*t^2*V3^2+9*V2*V4+36*t^2*V2*V4)/(288*V2^2),(-385*V3^4-940*t^2*V3^4+918*V2*V3^2*V4+1800*t^2*V2*V3^2*V4-201*V2^2*V4^2-204*t^2*V2^2*V4^2-456*V2^2*V3*V5-672*t^2*V2^2*V3*V5+120*V2^3*V6+96*t^2*V2^3*V6)/(13824*V2^5)},
DerivativesList=Prepend[NestList[Simplify[F[x]D[#,x]]&,F[x]*V'[x],5]/.{Derivative[n_][V][x]:>n!Symbol["v"<>ToString[n]],Derivative[n_][F][x]:>n!Symbol["f"<>ToString[n]],F[x]:>f0}/.v1->0//Rest,v0],
credits="The third-order WKB formula was obtained by \!\(\*ButtonBox[\"Sai Iyer and Clifford M. Will, Phys. Rev. D35 (1987) 3621\",BaseStyle->\"Hyperlink\",ButtonData->{URL[\"https://inspirehep.net/record/21079\"],None},ButtonNote->\"Click to open the INSPIRE page.\"]\)."},
Message[WKBFormulaOrder::filecorrupt];
{3,credits,{f0,f1,f2,f3,f4},{v0,v2,v3,v4,v5,v6},DerivativesList,{t,V0,V2,V3,V4,V5,V6},WKBOrderFactors[4,DefaultWKBOrder]}
];


(*Reading WKB data*)
{WKBFormulaOrder,credits,fSeriesVar,vSeriesVar,PotentialDerivatives,WKBOrdersVar,WKBOrdersRaw}=WKBordersfilename//ReadCompressedData//CheckWKBData;
WKBFormulaOrder::usage="WKBFormulaOrder is number of the WKB orders saved in the file WKBorders.\n"<>credits;


(*Selects argument for the function to expand in series*)
SelectAppropriateArgument[{x_Symbol,Infinity,__}]:={1/x};
SelectAppropriateArgument[{x_Symbol,__}]:={x};
SelectAppropriateArgument[_List]:={};
SelectAppropriateArgument[L__List]:=Join@@Map[SelectAppropriateArgument,{L}];
(*Transforms nested series to the matrix of the coefficients*)
SeriesCoefficients[L_List]:=Map[SeriesCoefficients,L];
SeriesCoefficients[S_SeriesData]:=SeriesCoefficients[S[[3]]];
SeriesCoefficients[x_]:=x;
(*Check if there are series*)
SeriesCoefficientsCheck[L_List]:=Map[SeriesCoefficientsCheck,L];(*What we do with the lists?*)
SeriesCoefficientsCheck[S_SeriesData]:=SeriesCoefficients[S];
SeriesCoefficientsCheck[x_]:=CompoundExpression[Message[SeriesSolve::nonseries,ToString[x,InputForm]],{}];
(*Solves the list of equations with respect to R and its derivatives*)
SolveSeriesCoefficientList[L_List,R_Symbol,opt:OptionsPattern[]]:=Solve[L==0,Union[Cases[L,R[__],\[Infinity]],Cases[L,Derivative[__][R][__],\[Infinity]]],opt];
(*Solves left==right with respect to R, assuming that R is a series expansion*)
SeriesSolve[Equal[left_,right_],R_Symbol,L__List,opt:OptionsPattern[]]:=SeriesSolve[left-right,R,L,opt];
(*Solves eq==0 with respect to R, assuming that R is a series expansion*)
SeriesSolve[eq_,R_Symbol,L__List,opt:OptionsPattern[]]:=With[{RSeries=Series[R@@SelectAppropriateArgument[L],L]},
Check[Map[{R->#}&,RSeries/.SolveSeriesCoefficientList[eq/.R->RSeries//SeriesCoefficientsCheck,R,opt]],{{}}]
];
SeriesSolve::nonseries="Unable to find series expansion for the expression (`1`).";
SeriesSolve::usage="SeriesSolve[equation,variable,series expansion parameters] solves equation using Solve with respect to the variable as a series expansion Series[variable,series expansion parameters].";


(*We need to be quiet to turn the SeriesData format test shit off*)
Quiet[
SolveEikonal[\[Omega]_Symbol==formula:SeriesData[\[Kappa]_Symbol,\[Infinity],_List,-1,order_Integer/;order>=0,1],\[CapitalKappa]_Symbol,opt:OptionsPattern[]]:=With[{SquaredFormula=formula^2//Normal},
With[{SquaredEikonal=Series[SquaredFormula,{\[Kappa],\[Infinity],-2}]//Normal},
(*The result is really series in \[Kappa]!*)
Normal[SeriesSolve[SquaredFormula-x \[Kappa]-SquaredEikonal,\[CapitalKappa],{\[Kappa],\[Infinity],order},opt]//First]/.x->(\[Omega]^2-SquaredEikonal)/\[Kappa]
]
]
];
SolveEikonal::usage="SolveEikonal[\[Omega]==beyond eikonal formula,\[CapitalKappa]] solves equation with respect to \[CapitalKappa], assuming that the eikonal formula is of the first order of the multipole number.";


(*Convert series data to the derivatives with respect to the tortoise coordinate*)
WKBOrderList[n_,f:{__},v:{__}]:=With[{l=Length[v]-Length[f]-1},WKBOrderList[n,If[l>0,Join[f,ConstantArray[0,l]],Drop[f,l]],v]/;l!=0];
WKBOrderList[n_,f:{__},v:{__}]:=With[{order=Length[v]/2},
If[WKBFormulaOrder<order,
Message[WKBFormula::loworder,order//ToString];
WKBOrderList[n,PotentialDerivatives/.Dispatch[Join[Apply[Rule,{fSeriesVar,Take[f,2*WKBFormulaOrder-1]}//Transpose,1],Apply[Rule,{vSeriesVar,Take[v,2*WKBFormulaOrder]}//Transpose,1]]]],
WKBOrderList[n,Take[PotentialDerivatives,2*order]/.Dispatch[Join[Apply[Rule,{Take[fSeriesVar,2*order-1],f}//Transpose,1],Apply[Rule,{Take[vSeriesVar,2*order],v}//Transpose,1]]]]
]/;IntegerQ[order]&&Length[f]==2*order-1
];
(*Return list of the WKB orders*)
WKBOrderList[n_,V:{__}]:=With[{args=Prepend[V,n+1/2],order=Length[V]/2},
If[WKBFormulaOrder<order,
Message[WKBFormula::loworder,order//ToString];
WKBOrdersRaw/.Dispatch[Apply[Rule,{WKBOrdersVar,Prepend[Take[V,2*WKBFormulaOrder],n+1/2]}//Transpose,1]],
Take[WKBOrdersRaw,order+1]/.Dispatch[Apply[Rule,{Take[WKBOrdersVar,2*order+1],Prepend[V,n+1/2]}//Transpose,1]]
]/;IntegerQ[order]
];
WKBOrderList::usage="WKBOrderList[n,{V0,V2,V3,V4...}] returns list of the eikonal WKB formula and the higher-order corrections, which can be used in the WKBOrderPade; n is the overtone number, V0 is the potential peak and V2, V3, V4... are the values of the derivatives at the potential peak.";


(*Return WKB formula bookmarking orders by factor \[Epsilon]*)
(*WKBSum[\[Epsilon]_,A_List]:=\[Epsilon] FromDigits[A//Reverse,\[Epsilon]];*)
(*Fun fact: FromDigits does not always work as expected if A is a list of lists!*)
WKBSum[\[Epsilon]_,A_List]:=A*\[Epsilon]^Range[A//Length]//Total;


WKBPade[0,0,A_List]:=0;
WKBPade[0,A_List]:=Total[A];
WKBPade[n_Integer/;n>0,0,A_List]:=Total[Take[A,n]]/;n<=Length[A];
WKBPade[d_Integer/;d>0,A_List]:=ReplaceAll[PadeApproximant[WKBSum[x,A],{x,0,{Length[A]-d,d}}],x->1]/;d<Length[A];
WKBPade[n_Integer/;n>0,d_Integer/;d>0,A_List]:=ReplaceAll[PadeApproximant[WKBSum[x,A],{x,0,{n,d}}],x->1]/;d+n<=Length[A];
WKBPade::usage="WKBPade[m,list] returns square of the frequency calculated with the WKB formula for m=0, and with the Pad\[EAcute] approximation with the denominator of order m; list can be generated by WKBOrderList function.";


(*Sum WKB orders*)
WKBSumList[A_List]:=Map[Total[Take[A,#]]&,Range[2,A//Length]];
(*Return all possible Pad\[EAcute] approximants*)
WKBPadeList[A_List]:=WKBPadeApply[WKBSum[x,A],{x,A//Length}]/.x->1;


(*Act separately for each overtone in the list*)
WKBPadeApply[L_List,{x_Symbol,n_Integer}]:=WKBPadeApply[#,{x,n}]&/@L;
(*Apply all possible Pad\[EAcute] approximants up to the order n*)
WKBPadeApply[expr_,{x_Symbol,n_Integer}]:=Map[PadeApproximantApply[expr,{x,0,#}]&,With[{},{#-Range[#]+1,Range[#]-1}//Transpose]]&/@Range[2,n];
(*Use PadeApproximant function only when it is not reduced to the series expansion - otherwise PadeApproximant produces some strange error with Join::heads in my Mathematica 7.0*)
PadeApproximantApply[expr_,{x_Symbol,x0_?NumericQ,{m_Integer/;m>0,0}}]:=Series[expr,{x,x0,m}]//Normal;
PadeApproximantApply[expr_,{x_Symbol,x0_?NumericQ,{m_Integer/;m>0,n_Integer/;n>0}}]:=PadeApproximantCheck[Series[expr,{x,x0,m+n}]//Normal,{x,x0,{m,n}}];
(*PadeApproximantApply[arg__]:=PadeApproximant[arg];*)


PadeApproximantCheck[expr_,{x_Symbol,x0_?NumericQ,{m_Integer/;m>0,n_/;n>0}}]:=Quiet[Check[
PadeApproximant[expr,{x,x0,{m,n}}]//If[Quiet[#/.{x->1}]//#===Indeterminate||#===ComplexInfinity&,Message[WKBFormulaPade::indet,m-1//ToString,n//ToString];PadeApproximantCheck[expr//DoublePrecisionInExpr,{x,x0,{m,n}}],#]&,
Message[WKBFormulaPade::precsm,m-1//ToString,n//ToString];PadeApproximantCheck[expr//DoublePrecisionInExpr,{x,x0,{m,n}}],N::"precsm"],N::"precsm"];
DoublePrecisionInExpr[expr_]:=ReplaceAll[expr,{_?PossibleZeroQ:>0,n_?NumericQ:>If[Precision[n]<\[Infinity],SetPrecision[n,Max[Precision[n]*2,MachinePrecision]],n]}];
WKBFormulaPade::precsm="Insufficient WKB-formula precision for P`1`/`2`. The working precision for the Pad\[EAcute] approximant has been doubled.";
WKBFormulaPade::indet="Indetermined result obtained for P`1`/`2`. The working precision for the Pad\[EAcute] approximant has been doubled.";


(*Return list of series coefficients*)
SeriesCoefficientsListExtract[S_SeriesData/;Last[S]===1]:=Join[ConstantArray[0,S[[-3]]],S[[3]]];
(*Return list of series coefficients for the expansion around R0*)
SeriesCoefficientsList[func_,{R_Symbol,R0_?NumericQ,o_}]:=Series[func,{R,R0,o}]//SeriesCoefficientsListExtract;
SeriesCoefficientsList[func_,{R_Symbol,R0_,o_}]:=ReplaceAll[Series[func,{R,x,o}]//SeriesCoefficientsListExtract,x->R0];


(*Expand the functions near the peak, where the peak can be either a number or a series expansion*)
CalculateSeriesForWKBFormula[o_Integer/;o>0,U_,F_,{Rule[R_Symbol,Rm_]}]:=CalculateSeriesForWKBFormula[o,U,F,Rule[R,Rm]];
CalculateSeriesForWKBFormula[o_Integer/;o>0,U_,F_,Rule[R_Symbol,Rm_]]:=With[{Fseries=SeriesCoefficientsList[F,{R,Rm,o-2}],Useries=Delete[SeriesCoefficientsList[U,{R,Rm,o}],2]},
If[ListQ[Fseries]&&ListQ[Useries],{Fseries,Useries},Message[WKBFormula::singular];$Failed]
];


(*Check FindRoot result*)
FundRootResultQ[{_Rule}]:=True;
FundRootResultQ[___]:=False;
(*Calculate numerically the position of the potential peak*)
CalculatePeakPosition[o_Integer/;o>0,U_,F_,{R_Symbol,R0_,FR_:FindRoot},precision_]:=With[{Vd=D[U,R],
prec=If[NumericQ[precision]&&Im[precision]==0&&precision>0,precision,Message[WKBFormula::wrongprecision];MachinePrecision]},
With[{Res=Check[FR[Vd==0,{R,R0},WorkingPrecision->prec],$Failed]},If[!FundRootResultQ[Res],Message[WKBFormula::nosolution];Return[$Failed]];
With[{Rm=R/.Res},If[!NumericQ[Rm],Message[WKBFormula::notnumeric];Return[$Failed]];
Res
]
]
];


WKBFormula[o_Integer/;o>0,U_,F_,L:{_Symbol,_,_:FindRoot},\[Nu]_,precision_:MachinePrecision]:=With[{Res=WKBFormula[o,U,F,CalculatePeakPosition[2*o,U,F,L,precision],\[Nu]]},
If[ListQ[Res],Res,$Failed]
];
WKBFormula[o_Integer/;o>0,U_,F_,{r_Rule},\[Nu]_]:=WKBFormula[o,U,F,r,\[Nu]];
WKBFormula[o_Integer/;o>0,U_,F_,L:{__List},\[Nu]_]:=Map[WKBFormula[o,U,F,#,\[Nu]]&,L];
WKBFormula[o_Integer/;o>0,U_,F_,r_Rule,\[Nu]_]:=With[{seriesdata=CalculateSeriesForWKBFormula[2*o,U,F,r]},
If[ListQ[seriesdata],
WKBOrderList@@Prepend[seriesdata,\[Nu]]//WKBSumList//Reverse//Sqrt//Append[#,r]&,
$Failed]
];
WKBFormula::usage="WKBFormula[O,V[r],f[r],r\[Rule]rm,n] calculates overtone n using WKB formulas up to the order O; rm is the potential peak position.\nWKBFormula[O,V[r],f[r],{r,r0},n,precision] calculates overtone n using WKB formulas up to the order O; r0 is the initial guess for the potential peak.";
WKBFormula::loworder="Unable to use the order `1`. Using the WKB formula of order "<>ToString[WKBFormulaOrder]<>".";
WKBFormula::wrongprecision="Precision must be a positive number. MachinePrecision is used for the computations.";
WKBFormula::nosolution="Unable to find the potential maximum.";
WKBFormula::singular="Cannot find Taylor expansion at a singular point.";
WKBFormula::notnumeric="Not a numeric value of the potential maximum.";


WKBFormulaPade[o_Integer/;o>0,U_,F_,L:{_Symbol,_,_:FindRoot},\[Nu]_,precision_:MachinePrecision]:=With[{Res=WKBFormulaPade[o,U,F,CalculatePeakPosition[2*o,U,F,L,precision],\[Nu]]},
If[ListQ[Res],Res,$Failed]
];
WKBFormulaPade[o_Integer/;o>0,U_,F_,{r_Rule},\[Nu]_]:=WKBFormulaPade[o,U,F,r,\[Nu]];
WKBFormulaPade[o_Integer/;o>0,U_,F_,L:{__List},\[Nu]_]:=Map[WKBFormulaPade[o,U,F,#,\[Nu]]&,L];
WKBFormulaPade[o_Integer/;o>0,U_,F_,r_Rule,\[Nu]_]:=With[{seriesdata=CalculateSeriesForWKBFormula[2*o,U,F,r]},
If[ListQ[seriesdata],
WKBOrderList@@Prepend[seriesdata,\[Nu]]//WKBPadeList//Sqrt,
$Failed]
];
WKBFormulaPade::usage="WKBFormulaPade[O,V[r],f[r],r\[Rule]rm,n] calculates overtone n using WKB formulas with Pad\[EAcute] approximants up to the order O; rm is the potential peak position.\nWKBFormulaPade[O,V[r],f[r],{r,r0},n,precision] calculates overtone n using WKB formulas with Pad\[EAcute] approximants up to the order O; r0 is the initial guess for the potential peak.";


(*Solve the equation for K*)
SolveE[K_Symbol,Eq_Equal]:=K/.First[Solve[Eq,K]];
(*Find solution for K, which is the nearest to the Eikonal value*)
SolveK[K_Symbol,Eikonal_?NumericQ,W2_?NumericQ,lst_List,precision_]:=Quiet[Map[K/.FindRoot[#==W2,{K,Eikonal},WorkingPrecision->precision]&,lst,{2}],{FindRoot::"precw",FindRoot::"lstol"}];
SolveK[K_Symbol,W2_?NumericQ,lst_List,precision_]:=SolveK[K,N[SolveE[K,First@First[lst]==W2],precision],W2,lst,precision];
SolveKAll[K_Symbol,W2_?NumericQ,lst_List,precision_]:=Quiet[Map[N[K/.Solve[#==W2,K],precision]&,lst,{2}],{Solve::"verif"}];


WKBCoeff[o_Integer/;o>0,W2_:0,U_,F_,L:{_Symbol,_,_:FindRoot},precision_:MachinePrecision]:=With[{Res=WKBCoeff[o,W2,U,F,CalculatePeakPosition[2*o,U,F,L,precision],precision]},
If[ListQ[Res],Res,{}] (*If something is wrong with the user-defined function, return {}.*)
]/;NumericQ[W2];
WKBCoeff[o_Integer/;o>0,W2:{__?NumericQ},U_,F_,L:{_Symbol,_,_:FindRoot},precision_:MachinePrecision]:=With[{Res=WKBCoeff[o,W2,U,F,CalculatePeakPosition[2*o,U,F,L,precision],precision]},
If[ListQ[Res],Res,{{}}] (*If something is wrong with the user-defined function, return {{}}.*)
];
WKBCoeff[o_Integer/;o>0,W2_:0,U_,F_,L:{__List},precision_:MachinePrecision]:=Map[WKBCoeff[o,W2,U,F,#,precision]&,L]/;NumericQ[W2];
WKBCoeff[o_Integer/;o>0,W2:{__?NumericQ},U_,F_,L:{__List},precision_:MachinePrecision]:=Map[WKBCoeff[o,W2,U,F,#,precision]&,L];


WKBCoeff[o_Integer/;o>0,W2_:0,U_,F_,{r_Rule},precision_:MachinePrecision]:=Flatten[WKBCoeff[o,{W2},U,F,{r},precision],1]/;NumericQ[W2];
WKBCoeff[o_Integer/;o>0,W2:{__?NumericQ},U_,F_,{r_Rule},precision_:MachinePrecision]:=With[{seriesdata=CalculateSeriesForWKBFormula[2*o,U,F,r]},
If[ListQ[seriesdata],
With[{eqs={WKBOrderList@@Prepend[seriesdata,K-1/2]//WKBSumList}},Append[First[SolveK[K,#,eqs,precision]]&/@W2//Transpose//Reverse,r]],
{{}}] (*If something is wrong with the series expansion, return {{}}.*)
];
WKBCoeff::usage="WKBCoeff[O,\[Omega]^2,V[r],f[r],r\[Rule]rm,precision] solves the WKB formulas up to the order O for given squared frequencies \[Omega]^2 with respect to the S-matrix coefficient; rm is the potential peak position.\nWKBCoeff[O,w^2,V[r],f[r],{r,r0},precision] solves the WKB formulas up to the order O for given squared frequencies \[Omega]^2 with respect to the S-matrix coefficient; r0 is the initial guess for the potential peak.";


WKBCoeffPade[o_Integer/;o>0,W2_:0,U_,F_,L:{_Symbol,_,_:FindRoot},precision_:MachinePrecision]:=With[{Res=WKBCoeffPade[o,W2,U,F,CalculatePeakPosition[2*o,U,F,L,precision],precision]},
If[ListQ[Res],Res,{}] (*If something is wrong with the user-defined function, return {}.*)
]/;NumericQ[W2];
WKBCoeffPade[o_Integer/;o>0,W2:{__?NumericQ},U_,F_,L:{_Symbol,_,_:FindRoot},precision_:MachinePrecision]:=With[{Res=WKBCoeffPade[o,W2,U,F,CalculatePeakPosition[2*o,U,F,L,precision],precision]},
If[ListQ[Res],Res,{{}}] (*If something is wrong with the user-defined function, return {{}}.*)
];
WKBCoeffPade[o_Integer/;o>0,W2_:0,U_,F_,L:{__List},precision_:MachinePrecision]:=Map[WKBCoeffPade[o,W2,U,F,#,precision]&,L]/;NumericQ[W2];
WKBCoeffPade[o_Integer/;o>0,W2:{__?NumericQ},U_,F_,L:{__List},precision_:MachinePrecision]:=Map[WKBCoeffPade[o,W2,U,F,#,precision]&,L];


WKBCoeffPade[o_Integer/;o>0,W2_:0,U_,F_,{r_Rule},precision_:MachinePrecision]:=First[WKBCoeffPade[o,{W2},U,F,{r},precision]]/;NumericQ[W2];
WKBCoeffPade[o_Integer/;o>0,W2:{__?NumericQ},U_,F_,{r_Rule},precision_:MachinePrecision]:=With[{seriesdata=CalculateSeriesForWKBFormula[2*o,U,F,r]},
If[ListQ[seriesdata],
With[{eq=WKBOrderList@@Prepend[seriesdata,K-1/2]//WKBPadeList},SolveKAll[K,#,eq,precision]&/@W2],
{{}}] (*If something is wrong with the series expansion, return {{}}.*)
];
WKBCoeffPade::usage="WKBCoeffPade[O,w^2,V[r],f[r],r\[Rule]rm,precision] finds all soltions to all equations with Pad\[EAcute] approximants up to the order O for given squared frequencies w^2 with respect to n-1/2; rm is the potential peak position.\nWKBCoeffPade[O,w^2,V[r],f[r],{r,r0},precision] finds all soltions to all equations with Pad\[EAcute] approximants up to the order O for given squared frequencies w^2 with respect to n-1/2; r0 is the initial guess for the potential peak.";


BasicWKBFormula[\[Nu]_,V_List]:=With[{o2=V//Length},WKBSum[1,WKBOrderList[\[Nu],V]]/;o2>1&&EvenQ[o2]];
BasicWKBFormula[\[Nu]_,V__]:=With[{o2={V}//Length},WKBSum[1,WKBOrderList[\[Nu],{V}]]/;o2>1&&EvenQ[o2]];
BasicWKBFormula::usage="BasicWKBFormula[n,{V0,V2...}] returns square of the overtone number n; V2, V3, V4... are the values of the derivatives at the potential peak.";


ThisPoint[_,{R_Symbol,R0_},WorkingPrecision->prec_]:=If[NumericQ[R0]&&NumericQ[prec]&&Im[prec]===0,{R->SetPrecision[R0,prec]},{R->R0}];
ThisPoint::usage="Mimics a solution returned by FindRoot.";


SelectWKBValues[L:{__?NumericQ}]:=L[[#]]&/@Join[#,#+1]&[Ordering[Rest[L]/Most[L]-1//Abs,IntegerPart[(Length[L]+1)/3]]];
CalcWKBMean[L:{__?NumericQ}]:=Mean[L]//{#,Abs[L-#]^2//Mean//Sqrt}&;
PadeAverage[L:{__List}]:=PadeAverage/@L;
PadeAverage[L:{__?NumericQ}]:=L//Cases[#,_?NumericQ]&//DeleteCases[#,_?PossibleZeroQ]&//If[Length[#]>1,#//SelectWKBValues//CalcWKBMean,L]&;
PadeAverage::usage="Averages values obtained using different Pad\[EAcute] approximants and estimates the order of error.";


QNMCoeff[w0_]=-I (#^2-Re[w0]^2)/(4Re[w0]Im[w0])&;
QNMCoeff[w0_,w1_]=-I (#^2-Re[w0]^2)/(4Re[w0]Im[w0]) (1+(Re[w0]-Re[w1])^2/(32Im[w0]^2)-(3Im[w0]-Im[w1])/(24Im[w0]))+I (Re[w0]-Re[w1])/(16Im[w0])+I (#^2-Re[w0]^2)^2/(16Im[w0]Re[w0]^2) (1/Re[w0]+(Re[w0]-Re[w1])^2/(4Im[w0]^2))-(I (#^2-Re[w0]^2)^3)/(32Re[w0]^5Im[w0]) (1+((Re[w0]-Re[w1])Re[w0])/(4 Im[w0]^2)+((Re[w0]-Re[w1])^2Re[w0]^2)/(16 Im[w0]^4)-((3Im[w0]-Im[w1])Re[w0]^2)/(12 Im[w0]^3))&;
QNMCoeff::usage="Returns the analytic approximation for the S-matrix coefficient using one or two quasinormal frequencies.";


GBFactor=(1+ E^(2 I \[Pi] #))^-1&;


End[];
Protect[SeriesSolve,WKBOrderList,WKBPade,BasicWKBFormula,WKBFormulaOrder,ThisPoint,PadeAverage,WKBFormula,WKBFormulaPade,WKBCoeff,WKBCoeffPade,SolveEikonal,QNMCoeff,GBFactor];
EndPackage[];
